using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
/*
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * Answer : 4613732
 * 
 */
namespace Euler
{
    class Problem2
    {
        public void answerProblem()
        {
            long n = 4000000;//four million 4 000 000 
            long a = 1;
            long b = 1;
            long result=0;

            Console.WriteLine("Fibonaacci ==");
            while (b<n)
            {
                long temp = a;
                a = b;
                b = b + temp;
                if (b % 2 == 0)
                {
                    result += b;
                }
                Console.Write(" " + b);
            }
            Console.WriteLine("\nProblem 2 Result ==" + result);
        }

    }
}
